### ISSUE TITLE
document.defaultView undefined

### ISSUE THREAD

**Issue by zicjin** [domisooo/taro-f2-react#14]
<img width="499" alt="image" src="https://github.com/domisooo/taro-f2-react/assets/199482/f5327038-febf-468f-be4d-86a27cf91aab">

<img width="407" alt="image" src="https://github.com/domisooo/taro-f2-react/assets/199482/777b8ad4-6ea0-47e1-b6cd-3d615c3f38d8">

微信开发者工具
taro:3.6.20 
不知为何没有document.defaultView

**Comment by domisooo** [comment]
是在 Web 场景下使用的吗？

**Comment by zicjin** [comment]
> 是在 Web 场景下使用的吗？

小程序。容器没有设置高宽就会这样
