### ISSUE TITLE
在微信小程序上，页面滚动图表不会随着滚动，并且饼图的点击事件不生效。

### ISSUE THREAD

**Issue by sugarZhang415** [domisooo/taro-f2-react#17]
`
import { useContext, useEffect, useMemo } from 'react';
import { Chart, Interval, PieLabel } from '@antv/f2';
import F2Canvas from 'taro-f2-react';
import { useImmer } from 'use-immer';

import { SAVE_MONEY_LOGS_MAP } from '@repo/shared/buryPoint/savings';
import { ACTIVE_TEXT_COLOR, BIZ_LOGS_ID, BUSINESS_INFO, LINE_COLOR, TEXT_COLOR } from '@repo/shared/constants';
import { tranNumber } from '@repo/shared/utils';
import { sendLog } from '@repo/shared/utils/sendLog';

import { WEEK_SAVE } from '../../constants';
import { SaveMoneyGlobalContext } from '../../context';

import { setInitLog } from './utils';

import './index.scss';

const PieCharts = (props) => {
  const { weekData, allData, selectTab } = props;
  const { weekBizType, allBizType, changeWeekBizType, changeAllBizType } = useContext(SaveMoneyGlobalContext);

  const [state, setState] = useImmer({
    list: [],
    selectedItem: null
  });

  const { list, selectedItem } = state;

  const handleClick = (value) => {
    const item = Array.isArray(value) ? value?.[0]?.origin : value;

    setState((draft) => {
      draft.selectedItem = item;
    });
    const type = item?.saveMoneyType;
    selectTab === WEEK_SAVE ? changeWeekBizType(type) : changeAllBizType(type);
    if (selectTab === WEEK_SAVE) {
      sendLog({ ...SAVE_MONEY_LOGS_MAP.WeekPieClick, MPieType: BIZ_LOGS_ID[type] });
    } else {
      sendLog({ ...SAVE_MONEY_LOGS_MAP.AllPieClick, APieType: BIZ_LOGS_ID[type] });
    }
  };

  // 设置饼图选中区域样式
  const setSelectedStyle = (record) => {
    const { yMax } = record;
    return {
      // 半径放大 1.1 倍
      r: yMax * 1.1,
      fillOpacity: 1
    };
  };

  // 饼图图例文案
  const showLabel1 = (value) => {
    const selectType = selectTab === WEEK_SAVE ? weekBizType : allBizType;
    return {
      text: BUSINESS_INFO[value.saveMoneyType]?.name + '省',
      fill: selectType === value?.saveMoneyType ? ACTIVE_TEXT_COLOR : TEXT_COLOR,
      fontWeight: selectType === value?.saveMoneyType ? 500 : 400,
      fontSize: 14
    };
  };

  // 饼图图例文案
  const showLabel2 = (value) => {
    const selectType = selectTab === WEEK_SAVE ? weekBizType : allBizType;
    const text =
      tranNumber(Number(value.saveMoneyAmount).toFixed(2))?.num +
      tranNumber(Number(value.saveMoneyAmount).toFixed(2))?.unit +
      '元';
    return {
      fill: selectType === value?.saveMoneyType ? ACTIVE_TEXT_COLOR : TEXT_COLOR,
      text,
      fontWeight: selectType === value?.saveMoneyType ? 500 : 400,
      fontSize: 14
    };
  };

  return (
    <div className="save-pie-charts">
      <div className="save-pie-charts-total">
        <div>累计省钱/元</div>
        <div className="save-pie-charts-total-price">{totalPrice}</div>
      </div>
      <F2Canvas pixelRatio={window.devicePixelRatio} key={selectTab} className="save-pie-charts-total-pie" force-use-old-canvas="true">
        <Chart
          data={list}
          coord={{
            type: 'polar',
            transposed: true,
            innerRadius: 0.65,
            radius: 0.75
          }}
        >
          <Interval
            x="saveMoneyTotalAmount"
            y="showValue"
            adjust="stack"
            color={{
              field: 'saveMoneyType',
              range: ['#FF5500']
            }}
            style={{ padding: 20, lineWidth: 4, stroke: '#fff' }}
            selection={{
              selectedStyle: setSelectedStyle,
              cancelable: false,
              unSelectedStyle: { fillOpacity: 0.2 },
              defaultSelected: [selectedItem]
            }}
          />
          <PieLabel
            sidePadding={10} //文本与画布左右的距离(Number)
            anchorOffset={12} //锚点的偏移量
            anchorStyle={{
              //锚点的样式
              fill: '' //锚点的颜色(String)
            }}
            inflectionOffset={12} //拐点的偏移量
            skipOverlapLabels //是否忽略重叠文本(false)
            activeShape //图形被选中的时, 是否激活图形(false)
            adjustOffset={12} // 发生调整时的偏移量
            lineStyle={{
              stroke: LINE_COLOR //连接线的样式
            }}
            label1={showLabel1}
            label1OffsetY={-1} //label1与连接线垂直方向的偏移, 位置可通过 label2OffsetY 调整（有兼容性问题）
            label2={showLabel2}
            label2OffsetY={1} //label2与连接线垂直方向的偏移（有兼容性问题）
            onClick={handleClick}
          />
        </Chart>
      </F2Canvas>
    </div>
  );
};

export default PieCharts;
`

![image](https://github.com/domisooo/taro-f2-react/assets/43158017/d1e91285-1567-4afe-928b-c9c65d192c3c)

**Comment by WangShuXian6** [comment]
怎么解决 页面滚动图表不会随着滚动 的？

**Comment by domisooo** [comment]
@WangShuXian6 根据实际测试，不管是 4.x 还是 5.x ，饼图还是线图，开发工具还是真机，滚动一切正常
```jsx
<View>
  <View>
    {Array.from({ length: 30 }, (_, index) => (
      <View className="item">{index + 1}</View>
    ))}
  </View>
  <View style={{ width: "100%", height: "260px" }}>
    <F2Canvas>
      <Chart
        data={data}
        coord={{
          transposed: true,
          type: "polar",
        }}
      >
        <Interval
          x="a"
          y="percent"
          adjust="stack"
          color={{
            field: "name",
            range: [
              "#1890FF",
              "#13C2C2",
              "#2FC25B",
              "#FACC14",
              "#F04864",
              "#8543E0",
            ],
          }}
        />
        <Legend position="right" />
      </Chart>
    </F2Canvas>
  </View>
  <View>
    {Array.from({ length: 30 }, (_, index) => (
      <View className="item">{index + 1}</View>
    ))}
  </View>
</View>
```
