### ISSUE TITLE
无法显示刻度

### ISSUE THREAD

**Issue by IceTeddy** [domisooo/taro-f2-react#19]
Taro:  3.6.23
"@antv/f2": "^5.4.2",
"taro-f2-react": "^1.1.2",

可以正常显示Line， 但是添加Axis后无法显示刻度信息

<img width="756" alt="image" src="https://github.com/domisooo/taro-f2-react/assets/1934749/b3930c34-097f-4e8b-9ece-7ec3db3e3204">

<img width="806" alt="image" src="https://github.com/domisooo/taro-f2-react/assets/1934749/74892004-4f79-4bc6-95c0-cdc3f1fe4900">

**Comment by domisooo** [comment]
问题是由于 @antv/f2 5.x API 的调整引起的，预计周末更新修复
可暂时回退到 @antv/f2 4.x 版本

**Comment by domisooo** [comment]
已发布 1.2.0 版本，兼容 @antv/f2 v5.x 版本

**Comment by IceTeddy** [comment]
感谢大佬！明天我公司更新试试！
