### ISSUE TITLE
TypeError: Cannot read property 'getPropertyValue' of undefined

### ISSUE THREAD

**Issue by hooliy** [domisooo/taro-f2-react#22]

**Comment by dyxxxyd** [comment]
+1, 希望大佬解决

**Comment by domisooo** [comment]
Hello，请给出 Error 的上下文信息

**Comment by dyxxxyd** [comment]
> Hello，请给出 Error 的上下文信息

<img width="543" alt="image" src="https://github.com/user-attachments/assets/f49f0d33-0e63-4a84-afb7-7b5486098ee2">

按照readme中的示例代码写的

**Comment by dyxxxyd** [comment]
> Hello，请给出 Error 的上下文信息

使用的是nutui，如果使用 View包裹会报这个错，但是使用ScrollView不会

**Comment by domisooo** [comment]
代码片段贴出来

**Comment by dyxxxyd** [comment]
> 代码片段贴出来

<img width="608" alt="image" src="https://github.com/user-attachments/assets/f3905b2f-0d95-46e5-9e4c-2301917acd80">

这样就会报错：TypeError: Cannot read property 'getPropertyValue' of undefined。去掉 View 就正常了

**Comment by dyxxxyd** [comment]
F2Canvas 上级元素必须设置height。例如：
`
<View styles={{height: '300px'}}>
    <F2Canvas>...</F2Canvas>
</View>
`
这样才不会报错
@hooliy

**Comment by hooliy** [comment]
> F2Canvas 上级元素必须设置height。例如： `<View styles={{height: '300px'}}> <F2Canvas>...</F2Canvas> </View>` 这样才不会报错 @hooliy

好的，谢谢！
