### ISSUE TITLE
无法正常展示图表

### ISSUE THREAD

**Issue by Anonymity94** [domisooo/taro-f2-react#6]
## 现象
控制台无报错，真机预览无报错，图表没有渲染出来

## 版本信息
- "@tarojs/taro": "3.4.13",
- "taro-f2-react": "^1.0.5",
- "@antv/f2": "^4.0.42",

## 效果
![image](https://user-images.githubusercontent.com/13148447/229689868-c58e9745-89df-48f7-b3c9-0cd8e151f03b.png)

**Comment by daniel-zd** [comment]
请提供报错信息

**Comment by daniel-zd** [comment]
@Anonymity94 
请更新到 v1.1.0 ，尝试问题是否已解决，具体更新内容查看 [releases](https://github.com/daniel-zd/taro-f2-react/releases)

**Comment by daniel-zd** [comment]
#3
